// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'alias'
  | 'aliasFullNames'
  | 'author-browser-tool-menu-clear-search'
  | 'author-browser-tool-menu-item-label'
  | 'cancel'
  | 'creatorID'
  | 'first-name'
  | 'firstName'
  | 'fix-caps'
  | 'itemCount'
  | 'last-name'
  | 'lastName'
  | 'pref-help'
  | 'refresh'
  | 'rename'
  | 'rename-for-prefix'
  | 'rename-for-suffix'
  | 'save-and-close'
  | 'show-author'
  | 'show-item'
  | 'swap'
  | 'title';
